### ISSUE TITLE
Latest version of ext.misc on CTAN appears to have a typo

### ISSUE THREAD

**Issue by marmotghost** [Qrrbrbirlbel/tikz-extensions#6]
I was trying to use the `ext.misc` library after updating it with the TeX Live Utility. It appears to have now a misplaced `}`. Here is a minimal non-working example:
```
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{ext.misc}
\begin{document}
Hello
\end{document}
```
This example complains with 
```
(/usr/local/texlive/2023/texmf-dist/tex/generic/tikz-ext/pgfkeyslibraryext.pgfk
eys-plus.code.tex
(/usr/local/texlive/2023/texmf-dist/tex/plain/pgf/math/pgfmath.tex)
! Too many }'s.
l.107 }
```
Inspecting `pgfkeyslibraryext.pgfkeys-plus.code.tex` seems to confirm that there is indeed an excess `}` in line 107, which may have to be removed.

**Comment by muzimuzhi** [comment]
(fixed in [`6a4eb30`](https://github.com/Qrrbrbirlbel/tikz-extensions/commit/6a4eb306ce567062e1a05b51794c110bb8d1a6e2#diff-0886619232cbcd23bf71d7f41d06eee0e0e59301931593c6acbde75cf4548771))
