### ISSUE TITLE
Package tikz Error: I did not find the tikz library 'paths.ortho'

### ISSUE THREAD

**Issue by AndreC75** [Qrrbrbirlbel/tikz-extensions#8]
This example does not work with the library `paths.ortho`, but does work with this one: `ext.paths.ortho`

```
\usetikzlibrary{paths.ortho}
\begin{tikzpicture}[very thick, rounded corners]
\draw[help lines] (-.25, -1.25) grid (2.25, 1.25);
\draw (0, 0) -|- (2, 1) --
(2, 0) -|-[ratio=.25] (0,-1) -- cycle;
\end{tikzpicture}
```

**Comment by Qrrbrbirlbel** [comment]
The package only provides a `ext.paths.ortho` library – not a `paths.ortho` library. This is a typo in the manual. There is another example with the same mistake.
